### ISSUE TITLE
Simple code in TS not working

### ISSUE THREAD

**Issue by anant-k-singh** [alexreardon/memoize-one#90]
I guess I am not using it correctly,

```typescript
import memoizeOne from 'memoize-one';

const print = (list: Array<number>): void => list.forEach(num => {
    console.log(num);
});

const mem_print = memoizeOne(print);

let list = [1,2,3];

mem_print(list);
mem_print(list);

list = [...list, 4];

mem_print(list);
```
Compiled from TS 3.8 to JS with `tsc index.js`
```javascript
"use strict";
var __spreadArrays = (this && this.__spreadArrays) || function () {
    for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
    for (var r = Array(s), k = 0, i = 0; i < il; i++)
        for (var a = arguments[i], j = 0, jl = a.length; j < jl; j++, k++)
            r[k] = a[j];
    return r;
};
exports.__esModule = true;
var memoize_one_1 = require("memoize-one");
var print = function (list) { return list.forEach(function (num) {
    console.log(num);
}); };
var mem_print = memoize_one_1["default"](print);
var list = [1, 2, 3];
mem_print(list);
mem_print(list);
list = __spreadArrays(list, [4]);
mem_print(list);
```
Output:
```
var mem_print = memoize_one_1["default"](print);
                                        ^

TypeError: memoize_one_1.default is not a function
    at Object.<anonymous> (D:\MyGit\plaints\index.js:14:41)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```
tsconfig
```json
{
	"compilerOptions": {
		"target": "ES2018",
		"esModuleInterop": true,
		"allowSyntheticDefaultImports": true,
		"strict": true,
		"module": "esnext",
		"moduleResolution": "node",
	}
}
```

**Comment by TrySound** [comment]
See big thread
https://github.com/alexreardon/memoize-one/issues/37

Shortly, enable esModuleInterop in your ts config.

**Comment by anant-k-singh** [comment]
Same thing with __esModuleInterop: true__.
My tsconfig
```json
{
	"compilerOptions": {
		"target": "ES2018",
		"esModuleInterop": true,
		"allowSyntheticDefaultImports": true,
		"strict": true,
		"module": "esnext",
		"moduleResolution": "node",
	}
}
```

**Comment by alexreardon** [comment]
Please reopen if this is still a problem
